# These are supported funding model platforms

github: [thehackersbrain]
patreon: thehackersbrain
open_collective: thehackersbrain
ko_fi: thehackersbrain
liberapay: thehackersbrain
issuehunt: thehackersbrain
otechie: thehackersbrain

