name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for visiting here and investing your valuable time, We will take a look at the request and will be back to you ASAP :)'
        pr-message: 'Thank You for investing your valuable time in here. We will take a look at the request and Inform you ASAP. :)'
